export const FAST_FOOD_RESTAURANTS = [
  {
    id: "mcdonalds",
    name: "McDonald's",
    logo: "🍔",
    categories: [
      {
        name: "Burgers",
        items: [
          {
            id: "big-mac",
            name: "Big Mac",
            description: "Two all-beef patties, special sauce, lettuce, cheese",
            calories: 550,
            protein: 25,
            carbs: 45,
            fat: 30,
            servingSize: "1 burger",
          },
          {
            id: "quarter-pounder",
            name: "Quarter Pounder with Cheese",
            description: "Quarter pound beef patty with cheese",
            calories: 520,
            protein: 30,
            carbs: 41,
            fat: 26,
            servingSize: "1 burger",
          },
          {
            id: "mcdouble",
            name: "McDouble",
            description: "Two beef patties with cheese",
            calories: 400,
            protein: 22,
            carbs: 33,
            fat: 20,
            servingSize: "1 burger",
          },
        ],
      },
      {
        name: "Chicken",
        items: [
          {
            id: "mcchicken",
            name: "McChicken",
            description: "Crispy chicken sandwich",
            calories: 400,
            protein: 14,
            carbs: 39,
            fat: 21,
            servingSize: "1 sandwich",
          },
          {
            id: "chicken-nuggets-10",
            name: "Chicken McNuggets (10 pc)",
            description: "10 piece chicken nuggets",
            calories: 420,
            protein: 24,
            carbs: 25,
            fat: 24,
            servingSize: "10 pieces",
          },
        ],
      },
      {
        name: "Sides & Drinks",
        items: [
          {
            id: "medium-fries",
            name: "Medium French Fries",
            calories: 320,
            protein: 4,
            carbs: 43,
            fat: 15,
            servingSize: "medium",
          },
          {
            id: "coke-medium",
            name: "Coca-Cola (Medium)",
            calories: 220,
            protein: 0,
            carbs: 58,
            fat: 0,
            servingSize: "21 fl oz",
          },
        ],
      },
    ],
  },
  {
    id: "chickfila",
    name: "Chick-fil-A",
    logo: "🍗",
    categories: [
      {
        name: "Chicken",
        items: [
          {
            id: "chicken-sandwich",
            name: "Chick-fil-A Chicken Sandwich",
            description: "Original chicken breast sandwich",
            calories: 440,
            protein: 28,
            carbs: 41,
            fat: 19,
            servingSize: "1 sandwich",
          },
          {
            id: "spicy-chicken",
            name: "Spicy Chicken Sandwich",
            description: "Spicy breaded chicken sandwich",
            calories: 460,
            protein: 28,
            carbs: 45,
            fat: 19,
            servingSize: "1 sandwich",
          },
          {
            id: "nuggets-8",
            name: "Chicken Nuggets (8 count)",
            calories: 250,
            protein: 27,
            carbs: 11,
            fat: 11,
            servingSize: "8 pieces",
          },
        ],
      },
      {
        name: "Sides",
        items: [
          {
            id: "waffle-fries-medium",
            name: "Waffle Potato Fries (Medium)",
            calories: 420,
            protein: 5,
            carbs: 45,
            fat: 24,
            servingSize: "medium",
          },
        ],
      },
    ],
  },
  {
    id: "tacobell",
    name: "Taco Bell",
    logo: "🌮",
    categories: [
      {
        name: "Tacos",
        items: [
          {
            id: "crunchy-taco",
            name: "Crunchy Taco",
            calories: 170,
            protein: 8,
            carbs: 13,
            fat: 9,
            servingSize: "1 taco",
          },
          {
            id: "soft-taco",
            name: "Soft Taco",
            calories: 180,
            protein: 9,
            carbs: 18,
            fat: 9,
            servingSize: "1 taco",
          },
        ],
      },
      {
        name: "Burritos",
        items: [
          {
            id: "bean-burrito",
            name: "Bean Burrito",
            calories: 350,
            protein: 13,
            carbs: 54,
            fat: 9,
            servingSize: "1 burrito",
          },
          {
            id: "burrito-supreme",
            name: "Burrito Supreme",
            calories: 380,
            protein: 14,
            carbs: 50,
            fat: 13,
            servingSize: "1 burrito",
          },
        ],
      },
    ],
  },
  {
    id: "subway",
    name: "Subway",
    logo: "🥖",
    categories: [
      {
        name: "6-Inch Subs",
        items: [
          {
            id: "turkey-breast",
            name: "Turkey Breast",
            calories: 280,
            protein: 18,
            carbs: 46,
            fat: 3.5,
            servingSize: "6-inch",
          },
          {
            id: "italian-bmt",
            name: "Italian B.M.T.",
            calories: 410,
            protein: 19,
            carbs: 46,
            fat: 16,
            servingSize: "6-inch",
          },
        ],
      },
    ],
  },
  {
    id: "kfc",
    name: "KFC",
    logo: "🍗",
    categories: [
      {
        name: "Chicken",
        items: [
          {
            id: "original-drumstick",
            name: "Original Recipe Drumstick",
            calories: 130,
            protein: 13,
            carbs: 3,
            fat: 7,
            servingSize: "1 piece",
          },
          {
            id: "crispy-breast",
            name: "Extra Crispy Breast",
            calories: 530,
            protein: 39,
            carbs: 16,
            fat: 35,
            servingSize: "1 piece",
          },
        ],
      },
    ],
  },
  {
    id: "wendys",
    name: "Wendy's",
    logo: "🍔",
    categories: [
      {
        name: "Burgers",
        items: [
          {
            id: "daves-single",
            name: "Dave's Single",
            calories: 570,
            protein: 29,
            carbs: 39,
            fat: 34,
            servingSize: "1 burger",
          },
          {
            id: "jr-cheeseburger",
            name: "Jr. Cheeseburger",
            calories: 280,
            protein: 15,
            carbs: 25,
            fat: 13,
            servingSize: "1 burger",
          },
        ],
      },
    ],
  },
];
